// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7Lm1phufS-l77XXScmIK9DgVRWt-_2EQ',
    appId: '1:75595274067:web:a829f41e4a8d462153b3a6',
    messagingSenderId: '75595274067',
    projectId: 'authntication-f92cd',
    authDomain: 'authntication-f92cd.firebaseapp.com',
    storageBucket: 'authntication-f92cd.appspot.com',
    measurementId: 'G-Q13VY7EL8X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_96ZsXtI6T034hmCA7uc3MDm8KboJAy8',
    appId: '1:75595274067:android:3487142e980f7e6d53b3a6',
    messagingSenderId: '75595274067',
    projectId: 'authntication-f92cd',
    storageBucket: 'authntication-f92cd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkbrjbKNX_VIBzEteEOrenYPs63ACa7AQ',
    appId: '1:75595274067:ios:8e4fd76a5663308d53b3a6',
    messagingSenderId: '75595274067',
    projectId: 'authntication-f92cd',
    storageBucket: 'authntication-f92cd.appspot.com',
    androidClientId: '75595274067-8ttolo872ved9oaiv47n1c6bqf2pe6g4.apps.googleusercontent.com',
    iosClientId: '75595274067-fii4ki9aetd5h3j3rpgvnq7o185c91rf.apps.googleusercontent.com',
    iosBundleId: 'com.example.jantagarage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkbrjbKNX_VIBzEteEOrenYPs63ACa7AQ',
    appId: '1:75595274067:ios:8e4fd76a5663308d53b3a6',
    messagingSenderId: '75595274067',
    projectId: 'authntication-f92cd',
    storageBucket: 'authntication-f92cd.appspot.com',
    androidClientId: '75595274067-8ttolo872ved9oaiv47n1c6bqf2pe6g4.apps.googleusercontent.com',
    iosClientId: '75595274067-fii4ki9aetd5h3j3rpgvnq7o185c91rf.apps.googleusercontent.com',
    iosBundleId: 'com.example.jantagarage',
  );
}
